export const mainCatalogItems = document.querySelectorAll('.catalog-item-img')
export const catalogItemArticles = document.querySelectorAll('.catalog-item-article')
export const catalogItem = document.querySelectorAll('.catalog-item')
export const popupMain = document.querySelector('.popup-main-menu')
export const btnClosePopup = document.querySelector('.btn-close')
export const btnMainMenu = document.querySelector('.header-main-menu') 
export const btnMainMenuPage1 = document.querySelector('.header-menu')